version: "3"
services:
  db:
    image: postgres:11.1-alpine


  web: &app_base
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL_CACHING: redis://redis:6379/0
      REDIS_URL_SIDEKIQ: redis://redis:6379/1


  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6382:6382'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/usr/src/app'
    env_file:
      - '.env'

  worker:
    <<: *app_base
    command: "sidekiq -C config/initializers/sidekiq.yml"
    entrypoint: []
    deploy:
      resources:
        limits:
          cpus: '${DOCKER_WORKER_CPUS:-0}'
          memory: '${DOCKER_WORKER_MEMORY:-0}'
    ports: []
    depends_on:
      - web


volumes:
  redis:
